Features/tcccd 83 jh
Texas-Policy-Lab/texas_child_care_deserts pull request #72
Opened 2022-02-11 19:33 UTC by holmesjoli

Very tiny changes

2022-02-14 16:17 UTC, sadierichardson requested changes
@holmesjoli just changed the variable name to match, but other than that, looks good!

2022-02-14 16:17 UTC, sadierichardson commented on R/frontline_dm.R
> +    dplyr::filter(reporting == "Reporting") %>%
```suggestion
    dplyr::filter(reporting_status == "Reporting") %>% 
```

2022-02-14 16:17 UTC, sadierichardson commented on R/frontline_dm.R
> +    dplyr::select(-reporting)
```suggestion
    dplyr::select(-reporting_status)
```

2022-02-15 14:12 UTC, holmesjoli commented
@sadierichardson good catch on both accounts. If you're ready to merge everything it all looks good to me!

2022-02-15 15:23 UTC, merged